### ISSUE TITLE
Animated Sprite Firing Warning On Actor Init

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp3#18]
**Describe the bug**
Every time actor is initialised the warning is fired. 
```
W 0:00:01:0205   factory.gd:35 @ create_actor(): Setting autoplay after the node has been added to the scene has no effect.
  <C++ Source>   scene/2d/animated_sprite_2d.cpp:433 @ set_autoplay()
  <Stack Trace>  factory.gd:35 @ create_actor()
                 unit.gd:18 @ spawn_actors()
                 stage_combat.gd:74 @ _spawn_actors()
                 stage_combat.gd:12 @ _ready()
```

**To Reproduce**
1. Init actor
2. See error

**Comment by eh-jogos** [comment]
This was also fixed at some point! I remember seeing this error, and I remember the fix was simple, but I can't remember what it was exactly and couldn't find it in the commit history.

**Comment by eh-jogos** [comment]
Or it was already fixed after I started and I'm confusing it with another error message
