### ISSUE TITLE
Actor Stats Not Initing

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp3#25]
**Describe the bug**
Actor Stats showing as 0

**To Reproduce**
1. Start game
2. Set breakpoint on any line of an Action that uses `_creator.stats.attack`
3. See error on break

**Expected behavior**
Stats should be loaded from ref_data global. 

**Screenshots**

![image](https://github.com/Snayff/nqp3/assets/23128268/c381d967-019e-4710-8219-10a132dedc3b)

![image](https://github.com/Snayff/nqp3/assets/23128268/99f4b4f2-7c92-4be3-80ea-ddbb2deea1e0)

![image](https://github.com/Snayff/nqp3/assets/23128268/621cb2ab-08bb-45f4-add5-29824bec18f3)

**Additional context**
Is there a reason only the first actor in each unit is called actor and the rest are `@CharacterBody2D@[num]`? Is this related? The node called "Actor" has proper stats. 
![image](https://github.com/Snayff/nqp3/assets/23128268/81e83a0d-53c6-489e-b422-661d5cbce8ca)

![image](https://github.com/Snayff/nqp3/assets/23128268/399c227c-a06d-4e1f-b343-b15676a4a3a5)

**Comment by snayff** [comment]
During `Factory.create_actor()` the unit has the correct `ActorStats`. At some point after instnatiation and being added to the `Unit._actors` variable it is getting changed.
